language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: beta
  - rust: nightly
script:
    - cargo build
    - cargo test
    - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo install clippy --force && cargo clippy -- -A doc_markdown -A cyclomatic_complexity -A collapsible_if ; fi'
    - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo install rustfmt --force &&  cargo fmt --all -- --write-mode=diff ; fi'
after_success: |
  # pip install --user autobahntestsuite &&
  # /home/travis/.local/bin/wstest -m fuzzingserver -s ./tests/fuzzingserver.json & SPID=$! &&
  # sleep 10 &&
  # cargo run --example autobahn-client --release &&
  # kill -9 ${FPID} &&
  # cargo run --example autobahn-server --release & SPID=$! &&
  # sleep 10 &&
  # /home/travis/.local/bin/wstest -m fuzzingclient -s ./tests/fuzzingclient.json &&
  # kill -9 ${SPID} &&
notifications:
  email: true
env:
  global:
    secure: U8csFsV9fsPB2CZ1SS+krd0YfWnMvUF7QznB8Vl1Oa/oImnYR4Z6DGIPdch1/WPbYpkX5FopvEgAbND2Jc7+Y9MDhxUlMGjHdPLZWgyypJtdZcifIkotnXsH69jB7MsFk1hkbvEIdFoaGgiDa+vjNh5rZhXL2FdycAels4YvgjLhM9I/PCu8jd+QjmdO4ftAFvBz8axV/e90SodMqlGSxc7GLi98IhW0SiCZSGmpr4aM9ZVpDUZ4lnMwKtl9vN3OkBrqZ/QOPk44865NQzXTVhyntbxT2jMJR5agH7j0OjZXQWOK3kBXpOQHMsfZP+oJVXWSNj6wbRHuPKDZXrG/tmQgTDKdzMHM9sAhr/xXk8mryREoWvDbBR8LysS208SgB8nB8rbNVKZuHzTfin7NOCHUy4hAXOUILqwZ+JKq+qQqv8Z2WrnmGdcbNZ8CS1Q3f3OhcYqODKV56reOzMpNNUHG8YcomC1t5yYn1AD4XYQ5Wx2itKFLrkhMqvqcsY2tM4q5uJOCv9+bibMKbotxGcXXNCGhB5CiQl6VvrJQDPUHHnd1FeadP/JKIS+ZSI/K2ZzX7w2YOFjjSK+zzGnJuvHFBpqcTNJEBNqahmu0+PHFrsLoWFdLKTYFZ8FKd0TTrhXRm3nFDY64DtXdA3j+R2VJnxbs8kprBQITMhdR3Cg=
