[package]
name = "ws"
version = "0.3.0"
authors = ["Jason Housley <HousleyJK@gmail.com>"]

description = "Lightweight, event-driven WebSockets for Rust."
documentation = "http://housleyjk.github.io/ws-rs/ws/"
repository = "https://github.com/housleyjk/ws-rs"
readme = "README.md"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"

[dependencies]
mio = { git = "https://github.com/carllerche/mio" }
log = "*"
httparse = "*"
sha1 = "*"
rand = "*"
url = "*"

[dev-dependencies]
env_logger = "*"
clock_ticks = "*"
clap = "*"
term = "*"
