[package]
authors = ["Jason Housley <HousleyJK@gmail.com>"]
description = "Lightweight, event-driven WebSockets for Rust."
documentation = "http://housleyjk.github.io/ws-rs/ws/"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"

name = "ws"
readme = "README.md"
repository = "https://github.com/housleyjk/ws-rs"
version = "0.4.2"

[dependencies]
httparse = "*"
log = "*"
mio = "*"
openssl = { version = "*", optional = true }
rand = "*"
sha1 = "*"
url = "*"

[dev-dependencies]
clap = "*"
env_logger = "*"
term = "*"
time = "*"

[features]
default = []
ssl = ["openssl"]
