[package]
authors = ["Jason Housley <HousleyJK@gmail.com>"]
description = "Lightweight, event-driven WebSockets for Rust."
documentation = "http://housleyjk.github.io/ws-rs/ws/"
keywords = ["websocket", "mio", "event-driven", "io", "web"]
license = "MIT"
name = "ws"
readme = "README.md"
repository = "https://github.com/housleyjk/ws-rs"
version = "0.4.5"

[dependencies]
httparse = "1.1.1"
log = "0.3.5"
mio = "0.5.0"
rand = "0.3.14"
sha1 = "0.1.1"
url = "0.5.7"

[dependencies.openssl]
optional = true
version = "0.7.6"

[dev-dependencies]
clap = "2.2.1"
env_logger = "0.3.2"
term = "0.4.4"
time = "0.1.34"

[features]
default = []
ssl = ["openssl"]
